steps:
  # 1. Determine environment from branch name
  - name: "gcr.io/cloud-builders/gcloud"
    id: "check-branch-name"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
          _ENV='production'
        else
          _ENV=$BRANCH_NAME
        fi
        echo "$_ENV" > /workspace/env_var.txt
        echo "Using environment: $_ENV"

  # 2. Simulate Gateway build (placeholder for actual build logic)
  - name: "gcr.io/cloud-builders/gcloud"
    id: "simulate-build"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        _ENV=$(cat /workspace/env_var.txt)
        echo "Simulating Gateway build for environment: $_ENV"
        echo "This is a placeholder. Add Docker build/push logic here when ready."

substitutions:
  _LOCATION: "us-east1"
  _ENV: "dev"

options:
  substitution_option: "ALLOW_LOOSE"
  logging: CLOUD_LOGGING_ONLY
