steps:
  # 1. Detect branch/environment
  - name: "gcr.io/cloud-builders/gcloud"
    id: "check-branch-name"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
          _ENV='production'
        else
          _ENV=$BRANCH_NAME
        fi
        echo "$_ENV" > /workspace/env_var.txt
        echo "Using environment: $_ENV"

  # 2. Simulate the build process (replace with real docker if needed later)
  - name: "gcr.io/cloud-builders/gcloud"
    id: "simulate-docker-build"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        _ENV=$(cat /workspace/env_var.txt)
        echo "Simulating Gateway build for environment: $_ENV"
        echo "This is a placeholder. Replace with docker build/push logic later."

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/notifications-deploys-nmas/versions/latest
      env: "URL_SLACK"

substitutions:
  _LOCATION: "us-east1"
  _ENV: "dev"

options:
  substitution_option: "ALLOW_LOOSE"
  logging: CLOUD_LOGGING_ONLY
