name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci

      - name: Auto assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0

      - name: Typescript check
        run: tsc --noEmit

      - name: Lint
        run: npm run lint:check

      - name: Prettier Format Check
        run: npm run format:check

      - name: Send slack error notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_USERNAME: 'Github Actions'
          SLACK_TITLE: 'Validation failed'
          SLACK_MESSAGE: '<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> - ${{ github.event.repository.name }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PR_URL }}
          SLACK_FOOTER: 'N+ Actions'
          MSG_MINIMAL: true

      - name: Check PR approvals
        id: check-approvals
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const approvals = new Set(
              reviews
                .filter(r => r.state === 'APPROVED')
                .map(r => r.user.login)
            );

            const count = approvals.size;
            core.setOutput("approvals", count);
            console.log(`Found ${count} approval(s)`);

      - name: Send slack approved PR update notification
        if: ${{ steps.check-approvals.outputs.approvals >= 2 }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FFC107'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_USERNAME: 'Github Actions'
          SLACK_TITLE: 'Content was added to this already approved PR'
          SLACK_MESSAGE: '<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> - ${{ github.event.repository.name }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PR_URL }}
          SLACK_FOOTER: 'N+ Actions'
          MSG_MINIMAL: true
