name: Pull Request Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify slack pr
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PR_URL }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULL_REQUEST_TITLE: ${{ github.event.repository.name }} | ${{ github.event.pull_request.title }}
          PULL_REQUEST_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{  github.event.pull_request.base.repo.owner.login }}
          PULL_REQUEST_COMPARE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
          PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          PULL_REQUEST_BASE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

          IS_SEND_HERE_MENTION: false
          MAKE_PRETTY: true
          MAKE_COMPACT: false
          IS_PR_FROM_FORK: false
          SEND_USER_ID_MENTIONS: U0431HRL37V,UAWKYSBAS,U04FVK2QA3V,U04N78RHPPT,UAVANGLJG,UAUSBGEMN,U08BWJQRU94,UAWE3T738,U076Q54E3JM,U051MB8L0P4,U04550UP1EG,U089MLW2E0L,U08HGFUMZBP,U08E0HTAM7T
        uses: jun3453/slack-pr-open-notification-action@v1.3.0
